### ISSUE TITLE
Opencv errors conduct while running on the YCBInEOAT dataset.

### ISSUE THREAD

**Issue by DCNSW** [wenbowen123/BundleTrack#11]
![image](https://user-images.githubusercontent.com/18084418/143882382-623af0c8-ffb9-4b13-b7f3-cadf845179f3.png)

**Comment by Rolling998** [comment]
Also the same error. Sorry to bother @wenbowen123 
![image](https://user-images.githubusercontent.com/50541193/144044327-d18d3e3a-deb1-4f2a-9f47-209ccbbe89e6.png)

**Comment by wenbowen123** [comment]
@Rolling998 @DCNSW do you have GPU on your computer? If so, which GPU is that?

**Comment by DCNSW** [comment]
@wenbowen123  NVIDIA GeFore RTX 3090

**Comment by wenbowen123** [comment]
@DCNSW @Rolling998 I was running on 2080 Ti. NVIDIA 3090 is a bit new. For 3090, you might need to build opencv from source with some additional settings for CUDA compilation inside docker container. I might provide an updated version for 3090 some time when I'm more free.

**Comment by DCNSW** [comment]
Thanks, this issue should be closed.

**Comment by Rolling998** [comment]
OK, thank you very much

**Comment by Hanziscool** [comment]
@DCNSW @Rolling998 have u guys got this running with building opencv from source? I am also having the same issue but with a newer NVIDIA A6000

**Comment by wenbowen123** [comment]
@DCNSW @Rolling998  
Here is a newer solution
https://github.com/wenbowen123/BundleTrack/issues/15
