### ISSUE TITLE
Unable to install bundletrack

### ISSUE THREAD

**Issue by alishan2040** [wenbowen123/BundleTrack#13]
Hello,

Thanks for providing the implementation for Bundle Track, you work is amazing. While I was trying this project, I'm repeatedly facing the issue with opencv. I've already compiled opencv 4.5 from source but the issue persists. 
![image](https://user-images.githubusercontent.com/30209002/146553083-c86621ff-93d2-432c-89cf-59e5b9170fce.png)

Can you please guide which version of opencv should work with bundle track. Also if you can include the requirements.txt file to the project, would be great.

Thanks,
Have a great day!,
Ali

**Comment by wenbowen123** [comment]
Hi, have you tried using the docker container, where the dependencies should have been set up? For opencv version, I remember it's 3.3.X. But it's not recommended to setup the env yourself as there would be quite some overhead.

**Comment by alishan2040** [comment]
Hi @wenbowen123, thanks for the reply.
I'm facing this issue when running this command **rm -rf build && mkdir build && cd build && cmake .. && make** as mentioned in the instructions. Should I skip this command,  and follow the rest?. I'm beginner to docker so have not clear idea about its usage.

Thanks

**Comment by tengxinyu151** [comment]
> Hello,
> 
> Thanks for providing the implementation for Bundle Track, you work is amazing. While I was trying this project, I'm repeatedly facing the issue with opencv. I've already compiled opencv 4.5 from source but the issue persists. ![image](https://user-images.githubusercontent.com/30209002/146553083-c86621ff-93d2-432c-89cf-59e5b9170fce.png)
> 
> Can you please guide which version of opencv should work with bundle track. Also if you can include the requirements.txt file to the project, would be great.
> 
> Thanks, Have a great day!, Ali

Hello! I am also trying this excellent project. This  is due to the copyright problem. For opencv versions above 4.3, just change it to cv::SIFT::create().

**Comment by wenbowen123** [comment]
@alishan2040 sift used to be in opencv-contrib. What @tengxinyu151 mentioned is correct. 
You can also safely comment that line since it's not used.
