### ISSUE TITLE
segmentation question

### ISSUE THREAD

**Issue by hahamini** [wenbowen123/BundleTrack#18]
Hi. I have a question.
I want to test in real time by connecting a camera after learning.
But I think vos segmentation is meant to be used only offline. Is there another way like lfnet communicates with bundletrack by communication?

**Comment by wenbowen123** [comment]
Hi, this is not yet supported. But you can write your own, as it's not hard to implement. For running on real robot, you can also use forward kinematics to do the segmentation which is eaiser.
