### ISSUE TITLE
Which checkpoint to use for transductive-vos?

### ISSUE THREAD

**Issue by WilliamKRobert** [wenbowen123/BundleTrack#21]
Hi, I downloaded models of transduction-vos according to README instructions. There are three checkpoints in the folder ```transductive-vos.pytorch```: ```davis_train.pth.tar```, ```davis_trainval.pth.tar``` and  ```youtube_train.pth.tar```. Which one should I use to reproduce your mask results?

**Comment by wenbowen123** [comment]
On NOCS we use `davis_trainval.pth.tar`
