### ISSUE TITLE
Can't find NOCS visualizations and path to the runnning_outputs

### ISSUE THREAD

**Issue by kausiksivakumar** [wenbowen123/BundleTrack#22]
In the instructions mentioned for running evaluations on NOCS, what is the directory of [PATH TO THE RUNNING OUTPUTS]? 
Also while running predictions on **NOCS**, I followed #15 's instructions and updated **Bundler.cpp** accordingly. Even after doing that, I could not find the the visualizations of NOCS stored in the results directory. I could only find a directory called poses that contains all the homogeneous transforms in a txt file. The directory **color_viz** does not contain any file. Could you help me with it. Thanks

I did three things, 
1) set log = 3 (in config_nocs.yml)
2) Add **_fm->vizKeyPoints(frame);** in Bundler.cpp
3) I did not quite understand what you were going for here https://github.com/wenbowen123/BundleTrack/issues/15#issuecomment-1004555934 . Could you clarify how to save the image?
This is my output that I received at terminal while running predictions on NOCS

```

New frame 0280
zmq start waiting for reply
zmq got reply
finding corres between 0280(id=1) and 0000(id=0)
frame 0280 and 0000 findNN too few match, 0280 status marked as FAILcolor file: ./NOCS/real_test/scene_1//../../real_test/scene_1/0281_color.png

```
The above message is for all the frames
Could you help me with this. Thanks

**Comment by kausiksivakumar** [comment]
Does it have something to do with the commented part of the code 
![image](https://user-images.githubusercontent.com/89941846/151071018-f85587b6-49c3-48c5-a3d7-62d214a12045.png)

**Comment by kausiksivakumar** [comment]
Also me changing debug_dir on **config_nocs.yml** doesn't seem to change the directory in which the results are stored

**Comment by kausiksivakumar** [comment]
Also I tried changing **log  = 3** in run_nocs.py manually
![image](https://user-images.githubusercontent.com/89941846/151075852-6259187a-1545-459d-9cb4-d36df1b5a8cf.png)
Now, when I run again, I get this as feedback
![image](https://user-images.githubusercontent.com/89941846/151075917-2cf30af9-ecfc-4fda-ae40-fedcdf5b6b7c.png)

**Comment by kausiksivakumar** [comment]
But me changing log = 3 in **config_nocs.yml** is not changing anything in the feedback. 
![image](https://user-images.githubusercontent.com/89941846/151076100-3fb792a6-aa09-4cdb-99f5-c4b32174ff19.png)
Could you please help me with this @wenbowen123 . I sincerely appreciate your time and effort. Thank you

**Comment by wenbowen123** [comment]
Hi, sorry for the late reply.

PATH TO THE RUNNING OUTPUTS: this refers to the debug_dir [in config_nocs.yml](https://github.com/wenbowen123/BundleTrack/blob/476d56f38527de1029306df6d9699151907df568/config_nocs.yml#L6)



> But me changing log = 3 in **config_nocs.yml** is not changing anything in the feedback. ![image](https://user-images.githubusercontent.com/89941846/151076100-3fb792a6-aa09-4cdb-99f5-c4b32174ff19.png) Could you please help me with this @wenbowen123 . I sincerely appreciate your time and effort. Thank you

What command did you run after it? Can you elaborate your complete steps. In particular, I 




> Also I tried changing **log = 3** in run_nocs.py manually ![image](https://user-images.githubusercontent.com/89941846/151075852-6259187a-1545-459d-9cb4-d36df1b5a8cf.png) Now, when I run again, I get this as feedback ![image](https://user-images.githubusercontent.com/89941846/151075917-2cf30af9-ecfc-4fda-ae40-fedcdf5b6b7c.png)

This should be the right way to do, but I'm not sure why you run into that error. Can you use some printing function to get some clues where it happens?

**Comment by wenbowen123** [comment]
Can you show me the file structures under `debug_dir: /tmp/BundleTrack/ ` if you didn't change the debug_dir.

**Comment by kausiksivakumar** [comment]
I did change the current output directory in **run_nocs.py** ans then changed the logs to 3

**Comment by kausiksivakumar** [comment]
When I change log to 3 in 
![image](https://user-images.githubusercontent.com/89941846/152018147-9dc207e2-f0c4-4b47-8c85-d842bc404710.png)
**config_nocs.py** i am able to get keypoints visualized but it is unable to find matches between images. 
![image](https://user-images.githubusercontent.com/89941846/152018303-70f2521a-d246-40a3-b019-0c1d10cf1e87.png)
I'm basically getting this error
Debug_dir: https://drive.google.com/drive/folders/1qz2XRhPVkEL3-zns36scEWF3-RE3mBZN?usp=sharing

**Comment by wenbowen123** [comment]
Yes, the keypoints detection look good. It should be the matching problem.

Can you change this line to =1 and re-build and run?
https://github.com/wenbowen123/BundleTrack/blob/476d56f38527de1029306df6d9699151907df568/CMakeLists.txt#L19

**Comment by kausiksivakumar** [comment]
Oh, it is already = 1

**Comment by kausiksivakumar** [comment]
I get this when I turn it to 0 
![image](https://user-images.githubusercontent.com/89941846/152431515-7c063408-44cd-4708-827d-4e9e372b9395.png)

**Comment by wenbowen123** [comment]
It is strange that you got frame 389 right after 0. Are the RGB files in your image folder complete and ordered?

**Comment by kausiksivakumar** [comment]
Yes they are. This matching error occurs at all the frames from 1 to 389. 

![image](https://user-images.githubusercontent.com/89941846/152651847-34cb2997-6da7-48d1-a536-b9233ed4cee4.png)
This continues till frame 389

**Comment by wenbowen123** [comment]
At https://github.com/wenbowen123/BundleTrack/blob/476d56f38527de1029306df6d9699151907df568/src/FeatureManager.cpp#L247

can you replace with this code then re-build and run and copy the output here?
```
void SiftManager::findCorresbyNN(std::shared_ptr<Frame> frameA, std::shared_ptr<Frame> frameB)
{
  assert(frameA->_id > frameB->_id);
  if (frameA->_keypts.size()==0 || frameB->_keypts.size()==0) return;

  const float max_dist_no_neighbor = (*yml)["feature_corres"]["max_dist_no_neighbor"].as<float>();
  const float cos_max_normal_no_neighbor = std::cos((*yml)["feature_corres"]["max_normal_no_neighbor"].as<float>()/180.0*M_PI);
  const float max_dist_neighbor = (*yml)["feature_corres"]["max_dist_neighbor"].as<float>();
  const float cos_max_normal_neighbor = std::cos((*yml)["feature_corres"]["max_normal_neighbor"].as<float>()/180.0*M_PI);

  const int H = frameA->_H;
  const int W = frameA->_W;

  bool is_neighbor = std::abs(frameA->_id-frameB->_id)==1;

  std::vector<cv::DMatch> matches_AB, matches_BA;
  std::vector< std::vector<cv::DMatch> > knn_matchesAB, knn_matchesBA;
  const int k_near = 5;

#if NO_OPENCV_CUDA
  cv::Ptr<cv::DescriptorMatcher> matcher = cv::DescriptorMatcher::create(cv::DescriptorMatcher::BRUTEFORCE);
  matcher->knnMatch( frameA->_feat_des, frameB->_feat_des, knn_matchesAB, k_near);
  matcher->knnMatch( frameB->_feat_des, frameA->_feat_des, knn_matchesBA, k_near);
#else
  cv::Ptr<cv::cuda::DescriptorMatcher> matcher = cv::cuda::DescriptorMatcher::createBFMatcher(cv::NORM_L2);
  matcher->knnMatch( frameA->_feat_des_gpu, frameB->_feat_des_gpu, knn_matchesAB, k_near);
  matcher->knnMatch( frameB->_feat_des_gpu, frameA->_feat_des_gpu, knn_matchesBA, k_near);
#endif

  printf("knn_matchesAB: %d, knn_matchesBA: %d\n",knn_matchesAB.size(),knn_matchesBA.size());
  pruneMatches(frameA,frameB,knn_matchesAB,matches_AB);

  pruneMatches(frameB,frameA,knn_matchesBA,matches_BA);
  printf("111 knn_matchesAB: %d, knn_matchesBA: %d\n",knn_matchesAB.size(),knn_matchesBA.size());

  collectMutualMatches(frameA,frameB,matches_AB,matches_BA);

  if (_matches[{frameA,frameB}].size()<5 && is_neighbor)
  {
    frameA->_status = Frame::FAIL;
    printf("frame %s and %s findNN too few match, %s status marked as FAIL", frameA->_id_str.c_str(), frameB->_id_str.c_str(), frameA->_id_str.c_str());
  }

}
```

**Comment by kausiksivakumar** [comment]
Yes, this is what I received for all the frames 
![image](https://user-images.githubusercontent.com/89941846/152691628-49a4fa83-e78f-432d-91f0-d9be0d3676b7.png)

**Comment by kausiksivakumar** [comment]
Is there something going wrong with the way I have installed packages?

**Comment by wenbowen123** [comment]
This is strange. I tested a while ago and didn't have this error. Can you update with this and repeat the steps? Also make sure you didn't change the code beyond the configuration files.
```
void SiftManager::findCorresbyNN(std::shared_ptr<Frame> frameA, std::shared_ptr<Frame> frameB)
{
  assert(frameA->_id > frameB->_id);
  if (frameA->_keypts.size()==0 || frameB->_keypts.size()==0) return;

  const float max_dist_no_neighbor = (*yml)["feature_corres"]["max_dist_no_neighbor"].as<float>();
  const float cos_max_normal_no_neighbor = std::cos((*yml)["feature_corres"]["max_normal_no_neighbor"].as<float>()/180.0*M_PI);
  const float max_dist_neighbor = (*yml)["feature_corres"]["max_dist_neighbor"].as<float>();
  const float cos_max_normal_neighbor = std::cos((*yml)["feature_corres"]["max_normal_neighbor"].as<float>()/180.0*M_PI);

  const int H = frameA->_H;
  const int W = frameA->_W;

  bool is_neighbor = std::abs(frameA->_id-frameB->_id)==1;

  std::vector<cv::DMatch> matches_AB, matches_BA;
  std::vector< std::vector<cv::DMatch> > knn_matchesAB, knn_matchesBA;
  const int k_near = 5;

#if NO_OPENCV_CUDA
  cv::Ptr<cv::DescriptorMatcher> matcher = cv::DescriptorMatcher::create(cv::DescriptorMatcher::BRUTEFORCE);
  matcher->knnMatch( frameA->_feat_des, frameB->_feat_des, knn_matchesAB, k_near);
  matcher->knnMatch( frameB->_feat_des, frameA->_feat_des, knn_matchesBA, k_near);
#else
  cv::Ptr<cv::cuda::DescriptorMatcher> matcher = cv::cuda::DescriptorMatcher::createBFMatcher(cv::NORM_L2);
  matcher->knnMatch( frameA->_feat_des_gpu, frameB->_feat_des_gpu, knn_matchesAB, k_near);
  matcher->knnMatch( frameB->_feat_des_gpu, frameA->_feat_des_gpu, knn_matchesBA, k_near);
#endif

  printf("knn_matchesAB: %d, knn_matchesBA: %d\n",knn_matchesAB.size(),knn_matchesBA.size());
  pruneMatches(frameA,frameB,knn_matchesAB,matches_AB);

  pruneMatches(frameB,frameA,knn_matchesBA,matches_BA);
  printf("111 knn_matchesAB: %d, knn_matchesBA: %d\n",knn_matchesAB.size(),knn_matchesBA.size());

  collectMutualMatches(frameA,frameB,matches_AB,matches_BA);

  if (_matches[{frameA,frameB}].size()<5 && is_neighbor)
  {
    frameA->_status = Frame::FAIL;
    printf("frame %s and %s findNN too few match: %d, %s status marked as FAIL\n", frameA->_id_str.c_str(), frameB->_id_str.c_str(), _matches[{frameA,frameB}].size(), frameA->_id_str.c_str());
  }

}
```

**Comment by kausiksivakumar** [comment]
Hmm, I still get the same error
![image](https://user-images.githubusercontent.com/89941846/153125418-cc4f1b75-70c3-4897-bbf0-c81fdeba2da1.png)
But that said, I did change a few things. For instance, I changed data, mask and debug directory in the yml file
![image](https://user-images.githubusercontent.com/89941846/153125813-ba292146-3347-46c3-a856-93c74fafc63b.png)
I found that the logs and the debug directory were getting overwritten so I had to change it in **run_nocs.py** file
![image](https://user-images.githubusercontent.com/89941846/153125931-a78b49f1-d4ef-4bb8-b010-0c15650949ee.png)
And I added 
![image](https://user-images.githubusercontent.com/89941846/153126000-19d14ce0-9ae6-4698-a124-7a7125074acc.png)
in **Bundler.cpp**

**Comment by kausiksivakumar** [comment]
Should I try reinstalling the process from scratch again?

**Comment by wenbowen123** [comment]
> I found that the logs and the debug directory were getting overwritten so I had to change it in run_nocs.py file

Hi, can you clarify how are these over-written (or over-written by what)? It should change the output folder of BundleTrack so the results will dumped there. 

Can you replace collectMutualMatches with below and repeat the previous steps? We might be close to find the problem.
```
void SiftManager::collectMutualMatches(std::shared_ptr<Frame> frameA, std::shared_ptr<Frame> frameB, const std::vector<cv::DMatch> &matches_AB, const std::vector<cv::DMatch> &matches_BA)
{
  auto &matches = _matches[{frameA, frameB}];

  for (int i=0;i<matches_AB.size();i++)
  {
    int Aid = matches_AB[i].queryIdx;
    int Bid = matches_AB[i].trainIdx;
    float uA = frameA->_keypts[Aid].pt.x;
    float vA = frameA->_keypts[Aid].pt.y;
    float uB = frameB->_keypts[Bid].pt.x;
    float vB = frameB->_keypts[Bid].pt.y;
    const auto &ptA = frameA->_cloud->at(std::round(uA), std::round(vA));
    const auto &ptB = frameB->_cloud->at(std::round(uB), std::round(vB));
    Correspondence corr(uA,vA,uB,vB, ptA, ptB, true);
    matches.push_back(corr);
  }
  printf("#matches=%d\n",matches.size());
  for (int i=0;i<matches_BA.size();i++)
  {
    int Aid = matches_BA[i].trainIdx;
    int Bid = matches_BA[i].queryIdx;
    float uA = frameA->_keypts[Aid].pt.x;
    float vA = frameA->_keypts[Aid].pt.y;
    float uB = frameB->_keypts[Bid].pt.x;
    float vB = frameB->_keypts[Bid].pt.y;
    const auto &ptA = frameA->_cloud->at(std::round(uA), std::round(vA));
    const auto &ptB = frameB->_cloud->at(std::round(uB), std::round(vB));
    Correspondence corr(uA,vA,uB,vB, ptA, ptB, true);
    matches.push_back(corr);
  }
  printf("111 #matches=%d\n",matches.size());
}
```

**Comment by kausiksivakumar** [comment]
> 

The part that overwrites the waml file is in run_nocs.py (in run_one_scene_one_model function)
![image](https://user-images.githubusercontent.com/89941846/153968283-5320251f-e4d7-4bf3-84f3-faf48ae947a6.png)

**Comment by kausiksivakumar** [comment]
I changed CollectMutualMatches with the script given 
![image](https://user-images.githubusercontent.com/89941846/153975409-df9ce7db-e93d-40ae-b7b0-47334225a282.png)
I got this for all frame combination

**Comment by wenbowen123** [comment]
https://github.com/wenbowen123/BundleTrack/issues/9#issuecomment-995455933
this might be the problem. Are you running with a GPU and does the cuda program compile successfully?

**Comment by kausiksivakumar** [comment]
https://github.com/wenbowen123/BundleTrack/issues/22#issuecomment-1028387412 
This only works when I set this to 1

**Comment by wenbowen123** [comment]
Your laptop has `NVIDIA GeForce RTX 3050 Ti` which is relatively new. I remember some users have met similar issues using the newer GPUs. This repo has been tested on 2080 Ti. Other older GPUs may also work. I don't have newer GPUs to develop and test on my side, so there is not plan of supporting the new GPUs in near future. Another workaround will be rewriting all the cuda code by C++.

**Comment by wenbowen123** [comment]
We used driver 460 and CUDA 11.2

**Comment by kausiksivakumar** [comment]
Yes, it works. I believe as you said, the problem is with the newer GPUs. Also, the path to download the weights returns a 404 now. Thought I should bring it to your notice
