### ISSUE TITLE
Running Predictions on own RGBD Data

### ISSUE THREAD

**Issue by helen9975** [wenbowen123/BundleTrack#23]
Hi, thanks for releasing code for this paper.

When I try to use BundleTrack to run predictions on my own RGBD Data, there are some issues:

1. I prepared my directory similar to that in YCBInEOAT, 
``` 
mustard_easy_00_02
├── rgb
├── masks
├── depth
└── cam_K.txt
 ```

However, it appears that when I run the code, I get the following error

![image](https://user-images.githubusercontent.com/50860781/152212700-da9e4df5-d919-46ec-89a1-55d4e40a4e46.png)

**Was wondering what is the role of poses in the annotated_poses folder, and how can I generate such poses for my data?**

2. When I populate the annotated_poses folder with arbitrary poses, I am able to generate keypoints, however, I get an error along the lines of 

> frame # and # findNN too few match, # status marked as FAILIn saveNewframeResult

This error is printed for every frame in the sequence. This may be connected with the annotated_poses folder problem, but not sure how to generate poses to ensure that the keypoint correspondence algo works.

Thanks!

**Comment by wenbowen123** [comment]
1)the role of poses in the annotated_poses is for visualization. If you dont have these for your own data, you can simply create the meaningless pose files with the same format as those in YCBInEOAT. Each file could just have a 4x4 identity matrix. Just make sure the number of files is the same as the number of your rgb files.

2)[This ](https://github.com/wenbowen123/BundleTrack/issues/22)seems related and perhaps you can follow that thread and comment.
