### ISSUE TITLE
Can this code be used to track multiple objects in real time and provide objects poses?

### ISSUE THREAD

**Issue by Ckq-Sugar** [wenbowen123/BundleTrack#27]
Hello @wenbowen123 , I tested this code and it works as the text says. Object masks are required as a prerequisite when testing each dataset. Can the project track multiple objects of different categories at the same time? And provide the poses of multiple objects?

**Comment by wenbowen123** [comment]
Hi, multi-object tracking is not implemented out-of-box. But one straightforward way is to launch multiple BundleTracks and provide mask for each object to start tracking.

**Comment by Ckq-Sugar** [comment]
Okay, I know. Thank you for your reply.
