### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Spj-Zhao** [wenbowen123/BundleTrack#32]
(base) root@hung-Alienware-Aurora-R9:/home/hung/Desktop/BundleTrack# python scripts/run_nocs.py --nocs_dir /home/hung/Desktop/BundleTrack/NOCS --scene_id 1 --port 5555 --model_name can_arizona_tea_norm
/home/hung/Desktop/BundleTrack/scripts/../build/bundle_track_nocs /tmp/config_model_can_arizona_tea_norm_scene1.yml
K
591.013       0 322.525
      0 590.168 244.111
      0       0       1

Reading directory failed: /home/hung/Desktop/BundleTrack/NOCS/gts/real_test_text/scene_1/model_can_arizona_tea_norm/
Segmentation fault (core dumped)

could you please upload the _NOCS/gts/real_test_text/scene_1/model_can_arizona_tea_norm/_

**Comment by wenbowen123** [comment]
See if this https://github.com/wenbowen123/BundleTrack/issues/31#issuecomment-1111127391 works

**Comment by Spj-Zhao** [comment]
> See if this [#31 (comment)](https://github.com/wenbowen123/BundleTrack/issues/31#issuecomment-1111127391) works

Thanks a lot,it's solved.
