### ISSUE TITLE
"You Only Demonstrate Once: Category-Level Manipulation from Single Visual Demonstration"

### ISSUE THREAD

**Issue by v-bengbeng-v** [wenbowen123/BundleTrack#33]
Hi bowen,

Awosome job!
Regarding this paper, when will the source code be updated?

Best,
beng

**Comment by wenbowen123** [comment]
Hi, the key modules of the paper such as model-free 6D object pose tracking (this repo) and [grasping ](https://github.com/wenbowen123/catgrasp) are both available, though there is no plan to release the entire framework at this moment.
