### ISSUE TITLE
Core dump problem

### ISSUE THREAD

**Issue by YYYYYHC** [wenbowen123/BundleTrack#36]
Hi, after setting up the environment, I am caught with a segmentation fault.
The problem happens when the texture.obj is loaded into a PolygonMesh object by pcl::io::loadOBJFile (Dataloader.cpp line318). The terminal output is _Segmentation fault (core dumped)_. I am wondering if the textured.obj is too big for cpus to load.
I notice that you are using texture_simple.obj rather than the texture.obj, could you provide me the .obj files you have tested ( e.g. 021_bleach_cleanser) ?

**Comment by wenbowen123** [comment]
Hi, the texture_simple.obj can be obtained from YCBVideo dataset
https://drive.google.com/file/d/1gmcDD-5bkJfcMKLZb3zGgH_HUFbulQWu/view

**Comment by YYYYYHC** [comment]
> Hi, the texture_simple.obj can be obtained from YCBVideo dataset
> https://drive.google.com/file/d/1gmcDD-5bkJfcMKLZb3zGgH_HUFbulQWu/view

Very helpful, thanks a lot!
