### ISSUE TITLE
Is there anyway to run without docker

### ISSUE THREAD

**Issue by tianhaowuhz** [wenbowen123/BundleTrack#4]
we want to combine this method to other algorithm, and run on some server that can not use docker, is there any tutorial to configure from scratch?

**Comment by tianhaowuhz** [comment]
Thank you for your advice! And I think I have figured out how to setup the environment from scratch

**Comment by bibekyess** [comment]
@tianhaowuhz Hello, can you share how you setup the local environment? It would be a nice reference for others to try. :) Thanks!
