### ISSUE TITLE
How to run BundleTrack faster

### ISSUE THREAD

**Issue by kausiksivakumar** [wenbowen123/BundleTrack#40]
Hi Bowen, 

We were trying to run BundleTrack online. So far we were only able to reach around 2.5 fps. I saw that in your post that you were able to make it run at 10 fps online. Could you let me know what setting to change in the `config_ycb.yml` that tradeoffs accuracy for fast inference? Thanks

**Comment by wenbowen123** [comment]
Hi, For https://github.com/wenbowen123/BundleTrack/blob/master/config_nocs.yml
Below are a few places that can directly affect the speed. You can tune that best fits your need. Using the best GPU that you can will definitely make it overall faster without performance sacrifice.
```
max_BA_frames: lower for faster 
image_downscale: higher for faster 
ransac:   max_iter: lower for faster 
```
