### ISSUE TITLE
Run predictions on own RGBD data

### ISSUE THREAD

**Issue by Jie-fafa** [wenbowen123/BundleTrack#44]
python transductive-vos.pytorch/run_video.py --img_dir /data/Jieie/BundleTrackData/YCBInEOAT/0311_9/depth --init_mask_file /data/Jieie/BundleTrackData/YCBInEOAT/0311_9/one_mask.png --mask_save_dir /data/Jieie/BundleTrackData

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by wenbowen123** [comment]
Do you have a GPU?

**Comment by Jie-fafa** [comment]
Yes.But it's 3090

**Comment by wenbowen123** [comment]
As discussed in some older issues. The repo currently doesn't support newer GPUs yet, such as 3090. Please try on 2080 Ti or older. We may add support to the new GPUs in the future.
