### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by lovesuiyue** [wenbowen123/BundleTrack#45]
您好 ，编译是在docker环境编译还是在普通环境下编译，因为我在docker 环境下编译缺少cmakelist.txt文件。

**Comment by wenbowen123** [comment]
Did you edit `docker/run_container.sh` with your paths?

**Comment by lovesuiyue** [comment]
编译之后进入的是bash环境吗？

**Comment by lovesuiyue** [comment]
跑您的catcrasp 的docker环境进入的是catcrasp  ，但是跑这个demo进入的是bash 环境

**Comment by wenbowen123** [comment]
You should compile and run inside docker. Edit docker/run_container.sh with your paths so that you can find CMakelists.txt inside docker.

**Comment by lovesuiyue** [comment]
wen 博士，Bundletrack文件夹里面有两个docker文件夹，我应该在哪个里面运行bash run_container.sh呢？

**Comment by wenbowen123** [comment]
The one under root dir

**Comment by lovesuiyue** [comment]
sorry,我运行之后还是找不到cmakelist.txt文件, 这是在bundletrack目录下运行run_container.sh出现的警告

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

**Comment by wenbowen123** [comment]
Did you edit docker/run_container.sh with your paths?
