### ISSUE TITLE
No visualization output on YCB and custom data

### ISSUE THREAD

**Issue by zituka** [wenbowen123/BundleTrack#46]
Hi wenbowen :
    thx for your great job on bundletrack!
    I have some problem when running prediction on YCB data. There is no output on my /tmp/BundleTrack file but I get poses output txt.
![2f92a16ab6bd744439c1e09d88c57f3](https://user-images.githubusercontent.com/50441823/170703869-a4e6d537-17ad-449f-94a8-4a11e3de3389.png)

![3](https://user-images.githubusercontent.com/50441823/170702468-25203e39-b5d0-4ad3-b1a8-2100611d0f43.jpg)

and when I try to predict on my own rgbd data, it shows 

![1](https://user-images.githubusercontent.com/50441823/170702294-eb944449-2ed0-4d6c-ab56-9c431383fc3c.jpg)

I donot understand why it need a obj file or annotation file?

**Comment by wenbowen123** [comment]
The annotation file here refers to an initial pose. You can create a dummy txt file with identity 4x4 matrix, if your desired initial pose is set the same as camera. Or you can take the mean of the initial masked point cloud and set to the translation part in the initial pose matrix to set object center as the origin.

**Comment by zituka** [comment]
Thanks for your reply!
Now I want to do a visualization on my own RGBD dataset, so if I add the pose annotation file it could be done right?
AND, There is nothing in the 'color_viz' file when I want to visualization on YCB dataset, (the first and second screen shot), how can I see the visualization output on YCB dataset?

**Comment by PolarisXQ** [comment]
> Hi, if you provided the true mesh of the target object, as well as the correct initial pose, then you can visualize the point cloud overlay. You can try the example YCBInEOAT data to get an idea.
> 
> Yes, by default, the bounding box is not plotted.

Would you please be so kind to explain how to draw a bounding box or obtain bounding box results?

**Comment by wenbowen123** [comment]
@PolarisXQ you can refer to https://github.com/NVlabs/BundleSDF/issues/91
