### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by cuiliangxian** [wenbowen123/BundleTrack#49]
Hi，bowen，I met somes problem when setting up environmennt with your provided instructions. I check the file is not empty. can you please help me figure out this problem？
![image](https://user-images.githubusercontent.com/44837543/173212070-cd1dcd3c-8673-4126-ac3e-323eb89426cf.png)

**Comment by cuiliangxian** [comment]
the problem is solved, I missed to replace the path. But here comes another question. Did i forget some important files?
![image](https://user-images.githubusercontent.com/44837543/173223480-4ef404b9-0280-4cb3-b806-65b0ab656438.png)

**Comment by cynthia-you** [comment]
> the problem is solved, I missed to replace the path. But here comes another question. Did i forget some important files? ![image](https://user-images.githubusercontent.com/44837543/173223480-4ef404b9-0280-4cb3-b806-65b0ab656438.png)

I think you miss placed the obj_models path

**Comment by wenbowen123** [comment]
What's your problem? The .mtl file missing error can be ignored. You should still be able to run.

**Comment by cynthia-you** [comment]
> 

Thanks for you replay , the problem has been fixed. It was just a delay in communicating with another Docker port or a slow data read.

**Comment by cynthia-you** [comment]
> What's your problem? The .mtl file missing error can be ignored. You should still be able to run.

Thanks for you replay , the problem has been fixed. It was just a delay in communicating with another Docker port or a slow data read.
