### ISSUE TITLE
Confusion about the results of  customized dataset

### ISSUE THREAD

**Issue by cynthia-you** [wenbowen123/BundleTrack#52]
Hi , Dr. Wen. It's me again (emmbarrsed hhhhh).
After your guidance last time, my data set ran results, but there were some problems.
Below is my data sturcture:
|--x
|--|-annotated_poses #obj_in_camera, [R|T]  4*4 
    |-depth # png
    |-masks # png, backgroud:0, obj:1
    |-rgb  #png
    |-txt # obj_in_world [x,y,z,roll,pitch,yaw]
    |-cam_K.txt # camera intrinsic 
![111](https://user-images.githubusercontent.com/37206493/178439059-5004b076-ca09-4bfb-83ba-899b28bc2a12.png)

BUT, from [https://github.com/wenbowen123/BundleTrack/issues/34](url), i knew that the mask is computed by FK.  So, i add obj of my data. And the running log seems that it cannt find the correspondense between frames:

`(base) root@Fusion:/home/cy/PycharmProjects/BundleTrack# python scripts/run_ycbineoat.py --data_dir /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x --port 5555
/home/cy/PycharmProjects/BundleTrack/scripts/../build/bundle_track_ycbineoat /tmp/config_yamo_pixel_0708.yml
cam K=
430.222       0     320
      0 430.222     240
      0       0       1
ob_in_cam0
-3.82857e-16    -0.988652     0.150225          -50
           0     0.150225     0.988652            0
          -1  3.78512e-16 -5.75149e-17           10
           0            0            0            1

data has 101 images
Connected to port 5555
color file: /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x/rgb/0.png

New frame 0
zmq start waiting for reply
zmq got reply
color file: /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x/rgb/1.png
...
New frame 26
Frame 26 cloud is empty, marked FAIL, roi WxH=0.000000x7.000000
color file: /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x/rgb/27.png
...
New frame 100
Frame 100 cloud is empty, marked FAIL, roi WxH=0.000000x7.000000
color file: /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x/rgb/100.png
`
and the visualization is so weird, could you pls give me some advice? Thanx~~~~
![color_viz](https://user-images.githubusercontent.com/37206493/178440618-76cd6ec8-395a-4ee6-acc4-e42990131a9e.jpg)
![19_match_0_before_ransac](https://user-images.githubusercontent.com/37206493/178440627-13aca67a-ed53-42c5-8e07-f129bbeffc1e.jpg)

**Comment by cynthia-you** [comment]
> Can you verify your mask is correctly provided? It seems you still have two objects: the teeth template and the blue region in the segmented image.
> 
> The `ob_in_cam0` also looks suspectable.
> 
> Also please see if you can run on our provided dataset. That'll give you an idea about how the dataset should look like.



> Can you verify your mask is correctly provided? It seems you still have two objects: the teeth template and the blue region in the segmented image.
> 
> The `ob_in_cam0` also looks suspectable.
> 
> Also please see if you can run on our provided dataset. That'll give you an idea about how the dataset should look like.

_________________________________________________reply__________________________________________________________________
For ob_in_cam0 , since the image is fixed to the camera's view, I shifted its coordinate  from world to camera.
but i shift your ../bleach0/annotated_poses into 6d_pose , i found it seems that your object is defined under robot coordinate. And  I also see you have spatial conversion functions inside c++ and lf-net, so shouldnt i transform the coordinate from world to camera?

The masks file is really 迷幻啊.  Path, format and pixel value were match your dataset bleach0, but bunder.cpp doesn't load them. I just cannot figure out why...

**Comment by wenbowen123** [comment]
The spatial transformation in c++ and lf-net is not used, so it's fine. And our coordinate frame is by setting the initial frame's camera center as origin.

Your segmentation seems wrong. There are multiple regions.

You can increase the LOG and check if the keypoint detection is working. (you might want to find some previous issues discussing this)

**Comment by cynthia-you** [comment]
> Can you verify your mask is correctly provided? It seems you still have two objects: the teeth template and the blue region in the segmented image.
> 
> The `ob_in_cam0` also looks suspectable.
> 
> Also please see if you can run on our provided dataset. That'll give you an idea about how the dataset should look like.

---------------------------------------reply
![2_match_1_after_ransac](https://user-images.githubusercontent.com/37206493/178910018-727bff7d-d385-40a3-90fc-d9cff2d96eb8.jpg)

Finally, It works .
It's the API which read masks cused the problem.  In cpp, it used cv to read data, and i processed masks by PIL.Image, if i use img.convert('RGB'), although all channles is the same, but cv will read it in a colorful way; but img.convert('L') is what exactly the bleach0 matched

**Comment by BoBoINVIDICUS** [comment]
> Hi , Dr. Wen. It's me again (emmbarrsed hhhhh). After your guidance last time, my data set ran results, but there were some problems. Below is my data sturcture: |--x |--|-annotated_poses #obj_in_camera, [R|T] 4*4 |-depth # png |-masks # png, backgroud:0, obj:1 |-rgb #png |-txt # obj_in_world [x,y,z,roll,pitch,yaw] |-cam_K.txt # camera intrinsic ![111](https://user-images.githubusercontent.com/37206493/178439059-5004b076-ca09-4bfb-83ba-899b28bc2a12.png)
> 
> BUT, from [https://github.com/wenbowen123/BundleTrack/issues/34](url), i knew that the mask is computed by FK. So, i add obj of my data. And the running log seems that it cannt find the correspondense between frames:
> 
> `(base) root@Fusion:/home/cy/PycharmProjects/BundleTrack# python scripts/run_ycbineoat.py --data_dir /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x --port 5555 /home/cy/PycharmProjects/BundleTrack/scripts/../build/bundle_track_ycbineoat /tmp/config_yamo_pixel_0708.yml cam K= 430.222 0 320 0 430.222 240 0 0 1 ob_in_cam0 -3.82857e-16 -0.988652 0.150225 -50 0 0.150225 0.988652 0 -1 3.78512e-16 -5.75149e-17 10 0 0 0 1
> 
> data has 101 images Connected to port 5555 color file: /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x/rgb/0.png
> 
> New frame 0 zmq start waiting for reply zmq got reply color file: /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x/rgb/1.png ... New frame 26 Frame 26 cloud is empty, marked FAIL, roi WxH=0.000000x7.000000 color file: /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x/rgb/27.png ... New frame 100 Frame 100 cloud is empty, marked FAIL, roi WxH=0.000000x7.000000 color file: /home/cy/PycharmProjects/BundleTrack/yamo_pixel_0708/x/rgb/100.png ` and the visualization is so weird, could you pls give me some advice? Thanx~~~~ ![color_viz](https://user-images.githubusercontent.com/37206493/178440618-76cd6ec8-395a-4ee6-acc4-e42990131a9e.jpg) ![19_match_0_before_ransac](https://user-images.githubusercontent.com/37206493/178440627-13aca67a-ed53-42c5-8e07-f129bbeffc1e.jpg)

Hi, May I ask you how your data set organization is made?

**Comment by cynthia-you** [comment]
> 
At the end of README.md file of this repo, prepare your dataset like 
![image](https://user-images.githubusercontent.com/37206493/201586920-588e44ff-0b24-4829-9000-236992fc9d33.png)

**Comment by ShifeiDuan** [comment]
I had the same issue, how did you get the annotated_poses file?
