### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by dongho-Han** [wenbowen123/BundleTrack#54]
Hello. Thanks for the nice project you've made.
I got amazed by BundleTrack project, so I'm working with your code.
But, I got stuck in the visualization part.
Can you share how to draw the bounding box and 3 axes in the supplementary video?
By issue #48 , I found you share the bbox drawing code.
But, I can't get where to put that code.
Therefore, I want help drawing a bounding box and also a 3D axis.
Thanks.

**Comment by wenbowen123** [comment]
Hi, that code is just a function that takes input of the images and poses, etc.
You can put anywhere or as a standalone script once you load the results.
