### ISSUE TITLE
How can I get these files?

### ISSUE THREAD

**Issue by Fahrenheit200** [wenbowen123/BundleTrack#6]
It seems that somes files mentioned in DataLoader.cpp are not provided
`std::smatch what;
    std::regex_search(data_dir, what, std::regex("NOCS/.*"));
    _model_dir = data_dir;
    boost::replace_all(_model_dir, std::string(what[0]), "NOCS/obj_models/real_test/"+_model_name+".obj");
    _gt_dir = data_dir;
    boost::replace_all(_gt_dir, std::string(what[0]), "NOCS/gts/real_test_text/scene_" + std::to_string(_scene_id) + "/model_" + _model_name + "/");
    _scale_dir = data_dir;
    boost::replace_all(_scale_dir, std::string(what[0]), "NOCS/NOCS-REAL275-additional/model_scales/"+_model_name+".txt");`

Without these files, I fail to run the code.

**Comment by Fahrenheit200** [comment]
> Hi, can you run "python scripts/run_nocs.py --nocs_dir [PATH_TO_NOCS] --scene_id 1 --port 5555 --model_name can_arizona_tea_norm “this command? I followed the author's steps, but when I run it, I just get the error "Segmentation fault". Thank you!

I think we get the same error. And I found that this error occurred because the dataloader cannot find some files, which should be included in path of NOCS. So I come here to ask the author if he can provide these files.

**Comment by Fahrenheit200** [comment]
Now I have got the files from [https://github.com/hughw19/NOCS_CVPR2019](url). And there are some pkl files in /gts/real_test just as you mentioned before. @wenbowen123 Could you please tell me how to convert the pkl files? 
And another question, the filenames in /NOCS/NOCS-REAL275-additional/model_scales don't match the filenames used in DataLoader.cpp.

**Comment by wenbowen123** [comment]
@Fahrenheit200 @ldylab 
Hi, the text files have been uploaded and updated in [readme](https://github.com/wenbowen123/BundleTrack#run-predictions-on-nocs).
