### ISSUE TITLE
findNN too few match

### ISSUE THREAD

**Issue by foww-0001** [wenbowen123/BundleTrack#60]
Thanks for your sharing. I found that during to run the project, the two adjacent frames could not find enough match points。I follow the issue #9 #15 #48, but it didnt work.

**Comment by foww-0001** [comment]
This is my result in running the project:
1. before ransac
![1578966042231670661_match_1578966042136484471_before_ransac](https://user-images.githubusercontent.com/69777191/197513474-5ab4b43f-7658-496d-9ec5-0c158e5c697a.jpg)
2. color_viz
![color_viz](https://user-images.githubusercontent.com/69777191/197513483-9ccc71be-e72d-46f7-9a6a-0043548bac5e.jpg)
3. keypoints
![keypoints](https://user-images.githubusercontent.com/69777191/197513493-d531f0d5-8aaf-431a-994b-675c02b6017a.jpg)

**Comment by wenbowen123** [comment]
It seems your matching fails. Might be related to CUDA version.

**Comment by foww-0001** [comment]
Thanks for your reply. Do you mean knn matching problem?
```
// knnMatch输出每个点的K个匹配点
#if NO_OPENCV_CUDA
  cv::Ptr<cv::DescriptorMatcher> matcher = cv::DescriptorMatcher::create(cv::DescriptorMatcher::BRUTEFORCE);
  matcher->knnMatch( frameA->_feat_des, frameB->_feat_des, knn_matchesAB, k_near);
  matcher->knnMatch( frameB->_feat_des, frameA->_feat_des, knn_matchesBA, k_near);
#else
  cv::Ptr<cv::cuda::DescriptorMatcher> matcher = cv::cuda::DescriptorMatcher::createBFMatcher(cv::NORM_L2);
  matcher->knnMatch( frameA->_feat_des_gpu, frameB->_feat_des_gpu, knn_matchesAB, k_near);
  matcher->knnMatch( frameB->_feat_des_gpu, frameA->_feat_des_gpu, knn_matchesBA, k_near);
#endif
```

**Comment by foww-0001** [comment]
> Thanks for your reply. Do you mean knn matching problem?
> 
> ```
> // knnMatch输出每个点的K个匹配点
> #if NO_OPENCV_CUDA
>   cv::Ptr<cv::DescriptorMatcher> matcher = cv::DescriptorMatcher::create(cv::DescriptorMatcher::BRUTEFORCE);
>   matcher->knnMatch( frameA->_feat_des, frameB->_feat_des, knn_matchesAB, k_near);
>   matcher->knnMatch( frameB->_feat_des, frameA->_feat_des, knn_matchesBA, k_near);
> #else
>   cv::Ptr<cv::cuda::DescriptorMatcher> matcher = cv::cuda::DescriptorMatcher::createBFMatcher(cv::NORM_L2);
>   matcher->knnMatch( frameA->_feat_des_gpu, frameB->_feat_des_gpu, knn_matchesAB, k_near);
>   matcher->knnMatch( frameB->_feat_des_gpu, frameA->_feat_des_gpu, knn_matchesBA, k_near);
> #endif
> ```

but i try NO_OPENCV_CUDA=1, and has the same error

**Comment by foww-0001** [comment]
I open 'detectFeature' code, it works
```
void SiftManager::detectFeature(std::shared_ptr<Frame> frame)
```

**Comment by wenbowen123** [comment]
In some older issues, I've seen people mentioning the depth become all 0 after processing. Can you check if your depth is the case when doing feature matching?
