### ISSUE TITLE
There's no folder called annotated_poses

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [wenbowen123/BundleTrack#62]
Hi, wenbo:
   When I  predicted on my own RGBD data, Some error messages appear, as shown in the following figure:
![)@JB}GEL(RIR`0(5Q{YB` I](https://user-images.githubusercontent.com/102162738/201521608-9fc0c7c3-702b-4c9f-85fa-774601b8d306.png)
   But I followed your tutorial to create my own data set and didn't see the information about the folder "annotated_poses." Here's the structure of my data set:
![Z3{~%WE3{X$~L2%_0522YMU](https://user-images.githubusercontent.com/102162738/201521730-f636d987-7f86-4ce7-a022-669b62d24391.png)
Should I change some Settings in the file "run_ycbineoat.py"? Where to change?
Looking forward to your reply.

**Comment by BoBoINVIDICUS** [comment]
When I  simply create the meaningless pose files with the same format as those in YCBInEOAT, 
![image](https://user-images.githubusercontent.com/102162738/201522238-ad883593-8442-4d43-adc6-d69cec6394ca.png)

**Comment by Bear-kai** [comment]
The same problem! Have you solved it ?

**Comment by Bear-kai** [comment]
> The same problem! Have you solved it ?

OK. I found my problem is due to different nameing style of files in rgb/ and depth/. Make sure they have exactly the same name. (eg. rgb/0001.png vs. depth/0001.png)
