### ISSUE TITLE
A strange question

### ISSUE THREAD

**Issue by lgq-gpu** [wenbowen123/BundleTrack#65]
First of all, thank you for your contribution, I encountered a strange problem here, the program automatically stops when it runs to the Connected to port 5555, I use a graphics card 2060, there is no new problem, please help me to analyze, the card has been here for a long time.
![1](https://user-images.githubusercontent.com/90536733/204283018-03cea086-0efd-4f47-8a86-f6cf983b8143.png)

**Comment by wenbowen123** [comment]
Hi, sorry for the late reply. Can you add some printing around [here](https://github.com/wenbowen123/BundleTrack/blob/690b4e24ddd16a69a8ac5078514a702a0c7cd414/src/app/bundle_track_nocs.cpp#L68) to see where it stops exactly?

**Comment by lgq-gpu** [comment]
Thank you for your reply. I will try to output it. Thanks again
