### ISSUE TITLE
Both the camera and object move

### ISSUE THREAD

**Issue by Neal2020GitHub** [wenbowen123/BundleTrack#69]
Hi! What a nice work! I'm wondering how to use BundleTrack to handle the situation that both the camera and object move?

**Comment by wenbowen123** [comment]
regardless of the movement of camera or object or both, BundleTrack will be able to track the object->camera pose. If you are interested in getting their poses in the world, then you need some camera localization module, to get cam->world pose, and then the object->world pose can also be inferred.

**Comment by Neal2020GitHub** [comment]
Hi Bowen! Thanks for your reply! I was a bit confused about choosing camera or world as reference to compute pose change but now it seems both correct with reference to each coordinate.
