### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ZhiyangZhou24** [wenbowen123/BundleTrack#7]
Hi Bowen:
     When i run scripts/run_ycbineoat.py , it reported an error, it should be unable to find the file, and the error is:
     [pcl::OBJReader::readHeader] Could not find file '/media/bowen/e25c9489-2f57-42dd-b076-021c59369fec/DATASET/YCB_Video_Dataset/CADmodels/021_bleach_cleanser/textured.obj'.
[pcl::OBJReader::read] Problem reading header!
[pcl::OBJReader::readHeader] Could not find file '/media/bowen/e25c9489-2f57-42dd-b076-021c59369fec/DATASET/YCB_Video_Dataset/CADmodels/021_bleach_cleanser/textured.obj'.
[pcl::OBJReader::read] Problem reading header!
     How can i fix this?  May I ask whether you have not provided this document? Thanks!

**Comment by wenbowen123** [comment]
@ZhiyangZhou24 
I now understand your problem. You need to download the object models from YCB. See the updated readme.
https://github.com/wenbowen123/BundleTrack#run-predictions-on-ycbineoat
