### ISSUE TITLE
open3d and transformations not found

### ISSUE THREAD

**Issue by fritz-ebner** [wenbowen123/BundleTrack#70]
Hi. I'm trying to Run predictions on YCBInEOAT, using your bundletrack docker image.

I am able to run run_ycbineoat.py ok, but when I try to run the eval script (either eval_nocs.py or eval_ycbineoat.py), it first complained about No module for open3d. I loaded open3d in the docker container, then it complained about not having transformations.  When attempting to load transformations, it gave me a glibc incompatibility error, so feeling stuck.

Is this a known issue, or perhaps I'm doing something wrong?
any advice would be very helpful.
thanks.

Also, another maybe dumb question: The output of the network is a pose 4x4 transform.  How do you get a bounding cube from that?

**Comment by wenbowen123** [comment]
Can you try pip install those packages inside docker?

The 4x4 transform is the pose. You can apply that to the axis-aligned cuboid to get an oriented bounding cube at the right location.
