### ISSUE TITLE
BundleSDF release time

### ISSUE THREAD

**Issue by Neal2020GitHub** [wenbowen123/BundleTrack#71]
Hi Bowen! The results of your new work BundleSDF seem amazing! May I ask when you will release the code?

**Comment by wenbowen123** [comment]
Thanks for your interest! Due to some legal process, we are planning to release around CVPR in June. Please stay tuned.

**Comment by wenbowen123** [comment]
@Neal2020GitHub Just to update you, we have released the code at https://github.com/NVlabs/BundleSDF
