### ISSUE TITLE
Tracking + Reconstruction / Real Time

### ISSUE THREAD

**Issue by rlee3359** [wenbowen123/BundleTrack#73]
Hi, I just had a few questions.

I noticed in #71 you mentioned the code for SDF will be coming soon. However, in that paper, one of the baselines is BundleTrack+TSDF Fusion for reconstruction. I assume you use BundleTrack output poses + Segmentation + TSDF Fusion to create the reconstructions. Is there any chance you can release the code for this in the meantime?
(A follow up question for that is, did you also use Xmem for the segmentation tracking for the baseline?)

I also noticed you have a ROS docker container, and you mentioned in #51 working on ROS release for this code. Is there any update on that? If not, do you have any advice on how one can set this up to track poses in real time? 

One more question, is the 3090 docker container specifically for that card, or will it work on other modern cards (eg. 3080)

Cheers,
Rob

**Comment by wenbowen123** [comment]
For the docker, we released the dockerfile in [BundleSDF](https://github.com/NVlabs/BundleSDF), which should be compatible with BundleTrack too, and it should work for GPUs other than 3090.

I could not find time to continue on the ROS release. One can implement a ROS wrapper for BundleTrack to run.

We were using XMem for fair comparison. As for now, there is no plan to release the part of code. The result is much worse than what we could get from BundleSDF. If reconstruction is the purpose, it's thus recommended to use BundleSDF.
