### ISSUE TITLE
Any instructions for training the model on my own?

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [wenbowen123/BundleTrack#75]
Hi Bowen, thanks for your nice work. I am wondering if there are any instructions for training the model on my own. Looking forward to hearing from you.

**Comment by wenbowen123** [comment]
Please refer to [readme](https://github.com/wenbowen123/BundleTrack#run-predictions-on-your-own-rgbd-data) about the instructions. BundleTrack can be instantly applied to novel unseen objects without re-training.

You might also want to check our recent work [BundleSDF](https://github.com/NVlabs/BundleSDF) which can not only track but also reconstruct the object's textured model
