### ISSUE TITLE
About feature detection FAIL

### ISSUE THREAD

**Issue by zjchenCode** [wenbowen123/BundleTrack#77]
![X%_J `5 BP(CX9VJ~G_RZC9](https://github.com/wenbowen123/BundleTrack/assets/119160944/12c96ab1-09d6-47d9-914b-e2324f42867e)

**Comment by zjchenCode** [comment]
@wenbowen123 Hi，I followed your steps and tried the NOCS and YCBInEOAT datasets respectively, but there was a problem of feature detection fail. Do you know where the problem is?

**Comment by wenbowen123** [comment]
Can you make sure your depth image is in the right format? You can enable higher debug level to dump the point cloud and viz them.

**Comment by zjchenCode** [comment]
![image](https://github.com/wenbowen123/BundleTrack/assets/119160944/d98f8cad-2e6d-4b1d-a529-4798c0a859e3)
![image](https://github.com/wenbowen123/BundleTrack/assets/119160944/3a903b3e-ae88-4bdb-8621-64ab376f0658)

The depth file is obtained from bleach0. There are 663 images, I think it should be right.

**Comment by wenbowen123** [comment]
https://github.com/wenbowen123/BundleTrack/blob/5f87ddf7133f2f86bdae6a08c926ed80a70003ec/src/Bundler.cpp#L118
Before finding feature correspondence, can you check if the depth image values are normal? I remember there were some similar issues previously and it was because of the depth are all zeros.

**Comment by zjchenCode** [comment]
@wenbowen123 Hi, thank you for your help, I have already solve the problem about feature detection FAIL. I update CUDA version from 9.0 to 11.3. 

But now, there are some other problems, about FindNN too few match.
I refer to previous answers, but it doesn't seem to solve my problem.

![ad3ebb48baec0fb2811239f2095c5bf](https://github.com/wenbowen123/BundleTrack/assets/119160944/71bce353-1827-47c2-9acd-9dffa79a286c)

About the depth image values，like this：
![491a9f06f3d0475a52401f1d2b87553](https://github.com/wenbowen123/BundleTrack/assets/119160944/c4d5e150-98d2-405d-ac1a-4a22afa98735)

My server is two 3090, CUDA version is 11.3.

I also modified 

add_definitions(-DNO_OPENCV_CUDA=1),

 but it has no effect.

**Comment by zjchenCode** [comment]
@wenbowen123 

According to the current results, it seems that the values of ptA.z and ptB.z are too large, causing all of them to be filtered out. I don't know why.

**Comment by wenbowen123** [comment]
can you check if the depth is like this at the beginning (after read), or is it changed to such somewhere?

**Comment by zjchenCode** [comment]
@wenbowen123  Hi, 
![image](https://github.com/wenbowen123/BundleTrack/assets/119160944/a339430c-d228-4eb9-88dd-2de6a4a21d52)
 In this function：SiftManager::pruneMatches (FeatureManager.cpp)
![1691232255077](https://github.com/wenbowen123/BundleTrack/assets/119160944/61640069-8901-43be-a320-36752c55140f)
We can find that ptA.z and ptB.z are larger than 0.1.
But they will still be judged as less than 0.1, which is very strange.

**Comment by zjchenCode** [comment]
![1691233276352](https://github.com/wenbowen123/BundleTrack/assets/119160944/f6630ee4-948b-46c6-b913-a3eb8df80fbe)
![1691233292699](https://github.com/wenbowen123/BundleTrack/assets/119160944/6d820c74-938b-454d-8abc-0d68d99734a7)
The depth value becomes 0 at this place

**Comment by zjchenCode** [comment]
![a8654e82bf723dff868cc65b5972aa6](https://github.com/wenbowen123/BundleTrack/assets/119160944/cadbf00b-ed11-4b04-97c2-e1e13e514ddf)
![1efedee9458553ad8b426bc79daacbd](https://github.com/wenbowen123/BundleTrack/assets/119160944/9c050b18-77a9-4aa8-aa1d-ce7c94da9c57)

**Comment by wenbowen123** [comment]
your printing format is not right. Can you replace your `%d` by `%f` and retry?

**Comment by zjchenCode** [comment]
Thanks for your correction! The result is as follows：
![1691334704942](https://github.com/wenbowen123/BundleTrack/assets/119160944/f1be4d6b-3a2e-4200-ae77-041dc71800a6)
![1691334753121](https://github.com/wenbowen123/BundleTrack/assets/119160944/d2ac720b-ca2b-4305-9d08-4dba7a5321df)

**Comment by wenbowen123** [comment]
it seems like the depth is already 0 at the line you printed. Can you trace back where it happened like I said?
>can you check if the depth is like this at the beginning (after read), or is it changed to such somewhere?

**Comment by zjchenCode** [comment]
@wenbowen123 

I have solved all the problems. Thanks for your help ！

My GPU is 3090, 

I would like to offer a possible solution to this problem:

Modify the CMakeLists.txt file:

From：
`set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -Xcompiler;-fPIC;-gencode arch=compute_61,code=sm_61;-gencode arch=compute_75,code=sm_75;-O3;-std=c++11;-use_fast_math;--default-stream per-thread)`

To：
`set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -Xcompiler;-fPIC;-gencode arch=compute_61,code=sm_61;-gencode arch=compute_75,code=sm_75;-gencode arch=compute_86,code=sm_86;-O3;-std=c++11;-use_fast_math;--default-stream per-thread)`
