### ISSUE TITLE
about draw bbox

### ISSUE THREAD

**Issue by zjchenCode** [wenbowen123/BundleTrack#82]
In the draw_bbox function you provided, how are the bbox parameters obtained? Is it point cloud data? Do I need to save the cloud data of each result?

`def draw_bbox(K, img, ob_in_cam, bbox, color_id, linewidth=2):
 def search_fit(points):
   '''
   @points: (N,3)
   '''
   min_x = min(points[:, 0])
   max_x = max(points[:, 0])
   min_y = min(points[:, 1])
   max_y = max(points[:, 1])
   min_z = min(points[:, 2])
   max_z = max(points[:, 2])
   return [min_x, max_x, min_y, max_y, min_z, max_z]
 
 def build_frame(min_x, max_x, min_y, max_y, min_z, max_z):
   bbox = []
   for i in np.arange(min_x, max_x, 1.0):
           bbox.append([i, min_y, min_z])
   for i in np.arange(min_x, max_x, 1.0):
           bbox.append([i, min_y, max_z])
   for i in np.arange(min_x, max_x, 1.0):
           bbox.append([i, max_y, min_z])
   for i in np.arange(min_x, max_x, 1.0):
           bbox.append([i, max_y, max_z])
 
   for i in np.arange(min_y, max_y, 1.0):
           bbox.append([min_x, i, min_z])
   for i in np.arange(min_y, max_y, 1.0):
           bbox.append([min_x, i, max_z])
   for i in np.arange(min_y, max_y, 1.0):
           bbox.append([max_x, i, min_z])
   for i in np.arange(min_y, max_y, 1.0):
           bbox.append([max_x, i, max_z])
 
   for i in np.arange(min_z, max_z, 1.0):
           bbox.append([min_x, min_y, i])
   for i in np.arange(min_z, max_z, 1.0):
           bbox.append([min_x, max_y, i])
   for i in np.arange(min_z, max_z, 1.0):
           bbox.append([max_x, min_y, i])
   for i in np.arange(min_z, max_z, 1.0):
           bbox.append([max_x, max_y, i])
   bbox = np.array(bbox)
   return bbox
 
 cam_cx = K[0,2]
 cam_cy = K[1,2]
 cam_fx = K[0,0]
 cam_fy = K[1,1]
 
 target_r = ob_in_cam[:3,:3]
 target_t = ob_in_cam[:3,3]*1000
 
 target = copy.deepcopy(bbox)
 limit = search_fit(target)
 bbox = build_frame(limit[0], limit[1], limit[2], limit[3], limit[4], limit[5])
 
 bbox = np.dot(bbox, target_r.T) + target_t
 
 color = np.array([[255, 69, 0], [124, 252, 0], [0, 238, 238], [238, 238, 0], [155, 48, 255], [0, 0, 238], [255, 131, 250], [189, 183, 107], [165, 42, 42], [0, 234, 0]])
vis = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
 for tg in bbox:
   y = int(tg[0] * cam_fx / tg[2] + cam_cx)
   x = int(tg[1] * cam_fy / tg[2] + cam_cy)
 
   if x - linewidth < 0 or x + linewidth > 479 or y - linewidth < 0 or y + linewidth > 639:
     continue
 
   for xxx in range(x-linewidth+1, x+linewidth):
     for yyy in range(y-linewidth+1, y+linewidth):
       vis[xxx][yyy] = color[color_id]
 
 vis = cv2.cvtColor(vis, cv2.COLOR_RGB2BGR)
 return vis
`
@wenbowen123

**Comment by PolarisXQ** [comment]
Have you solves the problem? I am also trying to plot axes and bbox and got confused about the bbox parameters

**Comment by wenbowen123** [comment]
the bbox are the bounding box of the object mesh. You can refer to https://github.com/NVlabs/BundleSDF/issues/91
