### ISSUE TITLE
Error when running bash run_container.sh

### ISSUE THREAD

**Issue by NicCusinato** [wenbowen123/BundleTrack#87]
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/68e43b4b654b63cacdf81600a750a574c6769ae49ba27c2ed223bb2f69a334d5/merged/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file exists: unknown.
ERRO[0025] error waiting for container: context canceled

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by wenbowen123** [comment]
can you try this? https://github.com/NVIDIA/nvidia-container-toolkit/issues/289#issuecomment-1903945518
