### ISSUE TITLE
frame %s and %s findNN too few match, %s status marked as FAIL

### ISSUE THREAD

**Issue by Fahrenheit200** [wenbowen123/BundleTrack#9]
I have tried to run the code on both datasets, but both can't produce the correct result. The error message is produced by SiftManager::findCorresbyNN. It seems that it can't find any match points between any two frames. The size of _matches[{frameA,frameB}] is always 0. And the pose data produced finally are all the same, same as the initial pose. Could you please help me figure out the problem？@wenbowen123

**Comment by wenbowen123** [comment]
Can you check the output folder /tmp/BundleTrack?
There are some segmentation or keypoints visualization. Make sure they look good.

**Comment by Fahrenheit200** [comment]
@wenbowen123 I call SiftManager::vizKeyPoints and get the keypoints.jpg. And there's no problem wtih the keypoints detection. It can actually detect 500 keypoints. I think there is something wrong wtih findCorresbyNN. It can't do the feature correspondense correctly.

**Comment by wenbowen123** [comment]
In the config file, change the LOG to 2 and there will be more files logged in `/tmp/BundleTrack` for debugging. e.g. if you are running on NOCS, change this https://github.com/wenbowen123/BundleTrack/blob/48272977b3280da12c18cd10da03d08500540a4f/config_nocs.yml#L8

See if there is anything abnormal.

**Comment by liuzheMET** [comment]
I found that the depth map was set to zero, when the program use cuda to preprocess it

**Comment by wenbowen123** [comment]
@liuzheMET Can you upload (e.g. Google drive) your logged files so that I can take further look?

**Comment by wenbowen123** [comment]
@liuzheMET @Fahrenheit200 
This seems related https://github.com/wenbowen123/BundleTrack/issues/15

**Comment by Hanziscool** [comment]
@wenbowen123 i ran into the same issue again after #15

running 
```
python scripts/run_ycbineoat.py --data_dir /home/jrojas/YCBInEOAT/bleach0 --port 5555 --model_name 021_bleach_cleanser --model_dir /home/jrojas/YCBInEOAT/YCB_Video_Dataset/models/021_bleach_cleanser/textured_simple.obj
```

![errorfindNNcorres](https://user-images.githubusercontent.com/27131476/147554476-e1bcf049-da09-40cc-bc86-710315ebaaaf.png)
 my ycb config file
![data_debug_mask_model_dir](https://user-images.githubusercontent.com/27131476/147554616-658eb189-718f-4964-be21-8344a04bddb9.png)
![log_depth_bundle](https://user-images.githubusercontent.com/27131476/147554721-49c30193-41e3-40ea-95e2-b154a3ac1e65.png)
![key_sift_corres_ransac](https://user-images.githubusercontent.com/27131476/147554760-e00bfba1-0aa5-44fa-83c6-4db94502a624.png)
![ransac_p2p](https://user-images.githubusercontent.com/27131476/147554796-7e8c5dcc-3749-453c-b2c8-568745ee3a84.png)

**Comment by wenbowen123** [comment]
@Hanziscool let's discuss this in that issue.

**Comment by kausiksivakumar** [comment]
I have the same issue with NOCS, I found nothing except poses saved in the debug directory.

**Comment by kausiksivakumar** [comment]
![image](https://user-images.githubusercontent.com/89941846/151268767-0f5af0fd-5d5c-4e39-97d8-e0732cc5ba2b.png)
This is one of the visualizations in NOCS. I am attaching the debug output here
https://drive.google.com/drive/folders/1qz2XRhPVkEL3-zns36scEWF3-RE3mBZN?usp=sharing

**Comment by kausiksivakumar** [comment]
> I found that the depth map was set to zero, when the program use cuda to preprocess it

@liuzheMET Could you let me know where did you find that the depth map was set. Thanks

**Comment by foww-0001** [comment]
> @wenbowen123 I call SiftManager::vizKeyPoints and get the keypoints.jpg. And there's no problem wtih the keypoints detection. It can actually detect 500 keypoints. I think there is something wrong wtih findCorresbyNN. It can't do the feature correspondense correctly.

I have the same problem, i visual the keypoint result, it can detect 500 keypoints, and when it send to pruneMatches function, matches_AB will be zero.
